//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePassSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePassSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Img_16x16_Open {
            get {
                object obj = ResourceManager.GetObject("Img_16x16_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_16x16_Options {
            get {
                object obj = ResourceManager.GetObject("Img_16x16_Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_16x16_Plugin {
            get {
                object obj = ResourceManager.GetObject("Img_16x16_Plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_16x16_Sync {
            get {
                object obj = ResourceManager.GetObject("Img_16x16_Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_48x48_Open {
            get {
                object obj = ResourceManager.GetObject("Img_48x48_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_48x48_Password {
            get {
                object obj = ResourceManager.GetObject("Img_48x48_Password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Img_48x48_Sync {
            get {
                object obj = ResourceManager.GetObject("Img_48x48_Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to create/edit your %1 online settings?.
        /// </summary>
        internal static string Str_EditCreateQuestion {
            get {
                return ResourceManager.GetString("Str_EditCreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t rename this entry or your online password information will be lost..
        /// </summary>
        internal static string Str_EntryNotes {
            get {
                return ResourceManager.GetString("Str_EntryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an unhandled exception in the options provider..
        /// </summary>
        internal static string Str_ErrExceptionOptions {
            get {
                return ResourceManager.GetString("Str_ErrExceptionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no provider selected in the options..
        /// </summary>
        internal static string Str_ErrNoProviderSelected {
            get {
                return ResourceManager.GetString("Str_ErrNoProviderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open database..
        /// </summary>
        internal static string Str_ErrOpenDatabase {
            get {
                return ResourceManager.GetString("Str_ErrOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t retrieve KeePassSync options..
        /// </summary>
        internal static string Str_ErrOptions {
            get {
                return ResourceManager.GetString("Str_ErrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t initialize the %1 provider..
        /// </summary>
        internal static string Str_ErrProviderInitialization {
            get {
                return ResourceManager.GetString("Str_ErrProviderInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible connection issue.  Unable to retrieve databases.  Test your connection and try again..
        /// </summary>
        internal static string Str_ErrRetrieveDatabase {
            get {
                return ResourceManager.GetString("Str_ErrRetrieveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sync the database..
        /// </summary>
        internal static string Str_ErrSync {
            get {
                return ResourceManager.GetString("Str_ErrSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during options validation..
        /// </summary>
        internal static string Str_ErrValidatingOptions_Error {
            get {
                return ResourceManager.GetString("Str_ErrValidatingOptions_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during options validation, not connected..
        /// </summary>
        internal static string Str_ErrValidatingOptions_NotConnected {
            get {
                return ResourceManager.GetString("Str_ErrValidatingOptions_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occured during options validation..
        /// </summary>
        internal static string Str_ErrValidatingOptions_Timeout {
            get {
                return ResourceManager.GetString("Str_ErrValidatingOptions_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database doesn&apos;t have valid online credentials necessary for synchronization..
        /// </summary>
        internal static string Str_OptionsChanged {
            get {
                return ResourceManager.GetString("Str_OptionsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePassSync (%1).
        /// </summary>
        internal static string Str_PasswordEntryTemplate {
            get {
                return ResourceManager.GetString("Str_PasswordEntryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized database (%1).
        /// </summary>
        internal static string Str_Synced {
            get {
                return ResourceManager.GetString("Str_Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing database (%1)....
        /// </summary>
        internal static string Str_Syncing {
            get {
                return ResourceManager.GetString("Str_Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeePassSync.
        /// </summary>
        internal static string Str_Title {
            get {
                return ResourceManager.GetString("Str_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to try again?.
        /// </summary>
        internal static string Str_TryAgain {
            get {
                return ResourceManager.GetString("Str_TryAgain", resourceCulture);
            }
        }
    }
}
